<?php $this->render('common/header'); ?>
<?php  
if((!isset ($_SESSION['email_login']) == true) and (!isset ($_SESSION['pass_login']) == true))
{
	unset($_SESSION['email_login']);
	unset($_SESSION['pass_login']);
        session()->put('_erro', 'Erro Login');
        return redirect()->route('index');
	}

$logado = $_SESSION['email_login'];
?>

<div class="page-header">
    <h1><strong>Cadastro de Pessoa</strong></h1>
</div>
<div class="col-md-2 pull-right">
              <div class="glyphicon glyphicon-log-out"></div>
              <a href="<?=url()->route('login.logout');?>" class="btn btn-link">
                  Logout
              </a>
            </div>

<div class="row">
    <div class="col-md-6">
        <form action="<?=url()->route('cadastro.salvar');?>" method="post" class="form-horizontal" role="form">
            <fieldset>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="textinput">Nome:</label>
                    <div class="col-sm-6">
                        <input name="nome" type="text" placeholder="Nome" class="form-control" pattern="^[A-Za-z]{4,15}$" title="Digitar somente LETRAS, tamanho maximo 15 (Caracteres)!!!" required>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="textinput">Fone:</label>
                    <div class="col-sm-6">
                        <input name="fone" type="tel" placeholder="(11)99999-9999" class="form-control" pattern="\([0-9]{2}\)[0-9]{4,6}-[0-9]{3,4}$" title="ex: (11)99999-9999" required>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="textinput">Email:</label>
                    <div class="col-sm-6">
                        <input name="email" type="email" placeholder="Email" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="textinput">Senha:</label>
                    <div class="col-sm-6">
                        <input name="password" type="password" placeholder="Senha" class="form-control" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" title="Deve conter pelo menos um número e uma letra maiúscula e minúscula e pelo menos 8 ou mais caracteres" required>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <div class="pull-left">
                            <button type="submit" class="btn btn-primary">Cadastrar</button>
                        </div>
                    </div>
                </div>
                <?php if(session()->has('_sucesso')): ?>
                    <div class="alert alert-success" role="alert"><?=session()->getAndRemove('_sucesso');?></div>
                <?php endif;  ?>
                <?php if(session()->has('_erro')): ?>
                    <div class="alert alert-warning" role="alert"><?=session()->getAndRemove('_erro');?></div>
                <?php endif;  ?>
            </fieldset>
        </form>
        <a class="btn btn-info" href="<?=url()->route('index');?>">Voltar</a>
    </div>
</div>
<?php $this->render('common/footer'); ?>
