<?php $this->render('common/header');?>
<!-- The Modal -->
<div class="modal fade" id="myModal">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Logar</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <form role="form" method="post" action="<?=url()->route('login.logar');?>">
          <fieldset>
            <div class="form-group">
                <input class="form-control" placeholder="E-mail" name="email" type="text">
            </div>
            <div class="form-group">
              <input class="form-control" placeholder="Password" name="password" type="password" value="">
            </div>
            <div class="checkbox">
                <label>
                  <input name="remember" type="checkbox" value="Remember Me"> Lembra-me
                </label>
            </div>
            <input class="btn btn-lg btn-success btn-block" type="submit" value="Login">
          </fieldset>
        </form>
      </div>
        <?php if(session()->has('_sucesso')): ?>
            <div class="alert alert-success" role="alert"><?=session()->getAndRemove('_sucesso');?></div>
        <?php endif;  ?>
        <?php if(session()->has('_erro')): ?>
            <div class="alert alert-warning" role="alert"><?=session()->getAndRemove('_erro');?></div>
        <?php endif;  ?>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
      </div>

    </div>
  </div>
</div>
