<?php $this->render('common/header'); ?>

<div class="container">
    <div class="row vertical-offset-100">
    	<div class="col-md-4 col-md-offset-4">
    		<div class="panel panel-default">
			  	<div class="panel-heading">
			    	<h3 class="panel-title">Login</h3>
			 	     </div>

			  	<div class="panel-body">
            <form class="form-inline">
              <label for="email">Email:</label>
              <input class="form-control" placeholder="E-mail" name="email" type="text">
              <input class="form-control" placeholder="Password" name="password" type="password" value="">
              <div class="form-check">
                <label class="form-check-label">
                  <input class="form-check-input" type="checkbox"> Lembra-me
                </label>
              </div>
              <button type="submit" class="btn btn-primary">Logar</button>
            </form>
			    </div>
			  </div>
		</div>
	</div>
</div>
