<html>
<head>
    <title>Agenda - Digital Control</title>
    <link rel="stylesheet" href="<?=assets()->css('bootstrap.min.css');?>">
    <link rel="stylesheet" href="<?=assets()->css('main.css');?>">
    <link rel="stylesheet" href="<?=assets()->css('login.css');?>">
    <script type="text/javascript" src="<?=assets()->js('jquery.min.js');?>"></script>
    <script type="text/javascript" src="<?=assets()->js('login.js');?>"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
